### ISSUE TITLE
Submodule "auDeep" commit is old 

### ISSUE THREAD

**Issue by Tomoya-K-0504** [DeepSpectrum/DeepSpectrum#20]
Hi! I'm a participant of ComParE 2020 Challenge.
While executing "bash deepspectrum_generate.sh", I encountered this error
`ModuleNotFoundError: No module named 'audeep.backend.parsers.compare20_mask'`
Now I checked auDeep commit id, and I realized I should checkout newer than "44df74ba1cf4549033cd863134f0fbdaa36b7bf5".
After that, I did `pip install ./auDeep/` in DeepSpectrum python virtual environment under `./DeepSpectrum` repository and errors disappeared.
Hope this would help you.

**Comment by mauricege** [comment]
Hi! 

Sorry about that! I updated the submodule to the latest commit. This should fix the issue. I will also push a new build of the conda package which should be up in the next hour.

**Comment by Tomoya-K-0504** [comment]
Thank you very much for your quick work!!
