### ISSUE TITLE
Is there any example that tell me how to use this tool for deep audio feature extraction?

### ISSUE THREAD

**Issue by tzczsq** [DeepSpectrum/DeepSpectrum#22]
Hi,  I am interested in your developed tool. I want to have a command of how to use this tool for deep audio feature extraction. However, I am a newer. 
So, could you please give me an example that how to use this tool to directly extract audio features fastly and easily?
Thanks for your help.

**Comment by amirip** [comment]
Hi, give it a try with:
`deepspectrum features your_wav_file.wav -nl -en resnet50 -fl avg_pool -m mel -o feature.csv`
or take a look at this example [here](https://github.com/DeepSpectrum/DeepSpectrum#features-for-avec2018-ces).

**Comment by mauricege** [comment]
Marking this as solved.
