### ISSUE TITLE
Why is an audio extract not a one-dimensional feature data

### ISSUE THREAD

**Issue by qiaoqiaoda** [DeepSpectrum/DeepSpectrum#23]
Why is it that an audio extract is not one-dimensional characteristic data, but two-dimensional, and the output of the full connection layer should be one-dimensional.

**Comment by mauricege** [comment]
Hi qiaoqiaoda,

I am not sure I understand your question correctly. 

Deep Spectrum should extract one-dimensional feature vectors, i.e. one vector for every chunk of audio content. If you are experiencing different behavior, please add a separate issue describing your problem in detail (DS version, CLI options, expected output, actual output).

Cheers,
Maurice

**Comment by mauricege** [comment]
Marking this as solved.
